CLUSTER_NAME = "fiap-cluster"
NOME_REPOSITORIO = "producao"
REGION = "us-east-1"
CLUSTER_IDENTIFIER = "rds-cluster-fiap-b"
DB_DATABASE = "projetopedidos"
DB_USERNAME = "root"
DB_PASSWORD = "AquiNaoNadaPassara"
DB_PORT = "3306"