cluster_name = "fiap-cluster"
nome_repositorio = "producao"
region = "us-east-1"
cluster_identifier = "aurora-cluster-fiap-b"
DB_DATABASE = "projetofiap"
DB_USERNAME = "root"
DB_PASSWORD = "qwe1234567"