CLUSTER_NAME = "fiap-cluster"
NOME_REPOSITORIO = "producao"
REGION = "us-east-1"
CLUSTER_IDENTIFIER = "aurora-cluster-fiap-b"
DB_DATABASE = "projetofiap"
DB_USERNAME = "root"
DB_PASSWORD = "qwe1234567"